[GraphControl]
refresh = 2.0
utf8 = True

[Temp,Graphs]
edge,0 = False
tctl,0 = True
mt7921_phy0,0 = False
composite,0 = False
sensor2,0 = False

[Frequency,Graphs]
avg = False
core 0 = True
core 1 = True
core 2 = True
core 3 = True
core 4 = True
core 5 = True
core 6 = True
core 7 = True
core 8 = True
core 9 = True
core 10 = True
core 11 = True

[Util,Graphs]
avg = False
core 0 = False
core 1 = False
core 2 = False
core 3 = False
core 4 = False
core 5 = False
core 6 = False
core 7 = False
core 8 = False
core 9 = False
core 10 = False
core 11 = False

[Power,Graphs]

[Temp,Summaries]
edge,0 = True
tctl,0 = True
mt7921_phy0,0 = True
composite,0 = True
sensor2,0 = True

[Frequency,Summaries]
avg = True
core 0 = False
core 1 = False
core 2 = False
core 3 = False
core 4 = False
core 5 = False
core 6 = False
core 7 = False
core 8 = False
core 9 = False
core 10 = False
core 11 = False

[Util,Summaries]
avg = True
core 0 = False
core 1 = False
core 2 = False
core 3 = False
core 4 = False
core 5 = False
core 6 = False
core 7 = False
core 8 = False
core 9 = False
core 10 = False
core 11 = False

[Power,Summaries]

