return {
  { import = 'my.plugins.catppuccin' },
  { import = 'my.plugins.treesitter' },
  { import = 'my.plugins.treesitter-context' },
  { import = 'my.plugins.snacks-nvim' },
  { import = 'my.plugins.blink-cmp' },
  { import = 'my.plugins.mini' },
  { 'plenary.nvim', lazy = false },

  { import = 'my.plugins.conform' },
  { import = 'my.plugins.debug' },
  { import = 'my.plugins.flash' },
  { import = 'my.plugins.gitsigns' },
  { import = 'my.plugins.lazydev' },
  { import = 'my.plugins.oil' },
  { import = 'my.plugins.oil-git' },
  { import = 'my.plugins.otter' },
  { import = 'my.plugins.todo-comments' },
  { import = 'my.plugins.toggleterm' },
  { import = 'my.plugins.undotree' },
  { import = 'my.plugins.which-key' },
  { 'vim-sleuth', event = 'DeferredUIEnter' },
}
