name: Cache long builds
on:
  workflow_dispatch:
  push:
    branches:
      - update_flake_lock_action

jobs:
  cache-long-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1

      - uses: cachix/cachix-action@v14
        with:
          name: perchunpak
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: Disable AppArmor
        run: |
          # || true because https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2093797
          sudo aa-teardown || true
          sudo systemctl stop apparmor

      - run: nix build .#long-builds-to-cache

      - name: Retrieve PR number
        if: always()
        run: |
          PR_NUMBER=$(gh pr view update_flake_lock_action --json number --jq '.number')
          echo $PR_NUMBER
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
        id: pr_number

      - name: Comment PR
        if: always()
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: Packages were cached!
          pr-number: ${{ steps.pr_number.outputs.PR_NUMBER }}
